# Generated by Django 5.2.10 on 2026-02-01 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_channel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.channel'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
