# Generated by Django 5.2.10 on 2026-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_emailotp_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
