"""
Django settings for cre project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t0n(hwnc7z$&k9z=(n!hl1j%j5+at@!bdt06py2-l9l6%f2gqx'

# SECURITY WARNING: don't run with debug turned on in production!


# settings.py
try:
    R2_ACCESS_KEY_ID = config('CLOUDFLARE_R2_KEY_ID', cast=str)
    R2_SECRET_ACCESS_KEY = config('CLOUDFLARE_R2_SECRET', cast=str)
    R2_BUCKET_NAME = config('CLOUDFLARE_R2_BUCKET', cast=str)
    R2_ENDPOINT_URL = config('CLOUDFLARE_R2_ENDPOINT', cast=str)
    
    CLOUDFLARE_R2_CONFIG_OPTIONS = {
        "bucket_name": R2_BUCKET_NAME,
        "access_key": R2_ACCESS_KEY_ID,
        "secret_key": R2_SECRET_ACCESS_KEY,
        "endpoint_url": R2_ENDPOINT_URL,
        "default_acl": "public-read",  # yoki "private"
        "signature_version": "s3v4",
    }

except Exception as e:
    raise Exception("Error loading environment variables: " + str(e))

match config('DJANGO_ENV', default=False):
    case True | 'development':
        DEBUG = True
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'http://127.0.0.1:5501/', 'http://127.0.0.1:5501/index.html', '*']
    case False | 'production':
        DEBUG = False
        ALLOWED_HOSTS = ['yourdomain.com', 'http://127.0.0.1:5501/', 'http://127.0.0.1:5501/index.html', '*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django.contrib.sites',

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    
    'users.apps.UsersConfig',
    'videos.apps.VideosConfig',
    'interactions.apps.InteractionsConfig',
    'user_auth.apps.UserAuthConfig',
    'api.apps.ApiConfig',
    "channels",
]

ASGI_APPLICATION = "core.asgi.application"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    
    'allauth.account.middleware.AccountMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



SITE_ID = 1
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default="5432"),
        "OPTIONS": {
            "sslmode": "require",
            "connect_timeout": 10,
        },
    }
}

import os

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME'),
#         'USER': os.environ.get('DB_USER'),
#         'PASSWORD': os.environ.get('DB_PASSWORD'),
#         'HOST': os.environ.get('DB_HOST'),
#         'PORT': os.environ.get('DB_PORT'),
#         'OPTIONS': {
#             'sslmode': 'require',
#         },
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

match DEBUG:
    case True:
        STATICFILES_DIRS = [BASE_DIR / 'static']
    case False:
        STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)


SITE_ID = 1

# Allauth yangi versiya sozlamalari
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Email tasdiqlamasdan kirish

# Google orqali kirgan foydalanuvchini signup page ga yo'naltirilmasligi uchun
SOCIALACCOUNT_AUTO_SIGNUP = True  # Avtomatik signup
SOCIALACCOUNT_EMAIL_REQUIRED = False  # Email talab qilinmasin
SOCIALACCOUNT_QUERY_EMAIL = True  # Email so'ralsin
ACCOUNT_LOGOUT_ON_GET = True  # GET request bilan logout

# Signup formadan qo'shimcha ma'lumot so'ralmasligi uchun
SOCIALACCOUNT_FORMS = {}

# Google orqali kirgandan keyin qaerga yo'naltirilishi
LOGIN_REDIRECT_URL = '/'  # Yoki 'home'
SOCIALACCOUNT_LOGIN_ON_GET = True

# Agar yangi user bo'lsa, avtomatik yaratilishi
SOCIALACCOUNT_ADAPTER = 'user_auth.adapters.CustomSocialAccountAdapter'
